[tool.poetry]
name = "rabbitmq-olm-package-repo"
version = "0.0.1"
description = "A simple python script to generate OLM (Operator Lifecyle Manager) bundles"
authors = ["RabbitMQ-Service-Operator-team"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
