#@ load("@ytt:data", "data")
#@ load("@ytt:overlay", "overlay")
#@ clusterserviceversion = overlay.subset({"kind": "ClusterServiceVersion"})
#@ cluster_operator = overlay.subset({"metadata": {"name": "rabbitmq-single-active-consumer-operator.v*"}})
#@overlay/match by=overlay.and_op(clusterserviceversion, cluster_operator),expects="1+"
---
spec:
  install:
    spec:
      deployments:
        #@overlay/match by=overlay.subset({"name": "single-active-consumer-operator-controller-manager"}),expects="1+"
        -
          #@overlay/match missing_ok=True
          spec:
