apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: devopstales-catalog-3
  namespace: openshift-marketplace 
spec:
  displayName: devopstales
  publisher: devopstales
  sourceType: grpc
  image: danielepalaia/single-active-consumer-index:0.2.2 
  updateStrategy:
    registryPoll:
      interval: 1m
