apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: devopstales-catalog-2
  namespace: openshift-marketplace 
spec:
  displayName: devopstales
  publisher: devopstales
  sourceType: grpc
  image: docker.io/danielepalaia/operatorhub-topology-index:1.8.0 
  updateStrategy:
    registryPoll:
      interval: 1m
