apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: devopstales-catalog
  namespace: openshift-marketplace 
spec:
  displayName: devopstales
  publisher: devopstales
  sourceType: grpc
  image: us.gcr.io/cf-rabbitmq-for-k8s-bunny/rabbitmq-for-kubernetes-olm:0.0.0 
  updateStrategy:
    registryPoll:
      interval: 1m
