apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: devopstales-catalog-2
  namespace: openshift-marketplace 
spec:
  displayName: devopstales
  publisher: devopstales
  sourceType: grpc
  image: rabbitmqoperator/rabbitmq-for-kubernetes-messaging-olm-index:0.0.0
  updateStrategy:
    registryPoll:
      interval: 1m
