#@ load("@ytt:data", "data")
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: rabbitmq-operator
  namespace: rabbitmq-system-olm
spec:
  channel: stable 
  installPlanApproval: Automatic
  name: rabbitmq-cluster-operator
  source: rabbitmq-dev-catalog
  sourceNamespace: openshift-marketplace 
  startingCSV: #@ data.values.csv
