#@ load("@ytt:data", "data")
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: rabbitmq-dev-catalog
  namespace: openshift-marketplace 
spec:
  displayName: rabbitmq
  publisher: rabbitmq
  sourceType: grpc
  image: docker.io/danielepalaia/rabbitmq-for-kubernetes-olm-cluster-operator-index:0.0.0
  updateStrategy:
    registryPoll:
      interval: 1m
