apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: rabbitmq-messaging-operator
  namespace: rabbitmq-system
spec:
  channel: stable 
  installPlanApproval: Automatic
  name: rabbitmq-messaging-topology-operator
  source: rabbitmq-dev-catalog-2
  sourceNamespace: openshift-marketplace 
  startingCSV: rabbitmq-messaging-topology-operator.v1.13.0
