apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: trivy-operator
  namespace: rabbitmq-system-olm 
spec:
  channel: stable 
  installPlanApproval: Automatic
  name: rabbitmq-cluster-operator
  source: devopstales-catalog
  sourceNamespace: openshift-marketplace 
  startingCSV: rabbitmq-cluster-operator.v0.0.0 
