name: test-bundle

on:
  push:
    branches:
      - master
  pull_request:
    types:
      - opened
      - synchronize
  workflow_dispatch:
  
jobs:
  ci:
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.9]
        os: [ubuntu-22.04]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install carvel
        run: curl -L https://carvel.dev/install.sh | bash
      - name: Install and configure Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.4.2
          virtualenvs-create: true
          virtualenvs-in-project: false
      - name: poetry install
        run: poetry install --no-root
      - name: isort check-only
        run: poetry run isort --check-only .
      - name: black check
        run: poetry run black --check .
      - name: poetry run pytest
        run: poetry run pytest
